export default {
  dashboard: "/admin",
  storeManager: "/admin/store-manager",
  createStore: "/admin/create-store",
  detailsStore: "/admin/details-store",
  staffManager: "/admin/staff-manager",
  createStaff: "/admin/create-staff",
  detailsStaff: "/admin/details-staff",
  customerManager: "/admin/customer-manager",
  statistic: "/admin/statistic-store",
  detailsStatistic: "/admin/details-statistic-store",
  detailsStatisticCustomer: "/admin/details-statistic-customer",
  configPoint: "/admin/config-point",
  configGift: "/admin/config-gift",
  configSearch: "/admin/config-search",
  giftManager: "/admin/gift-manager",
  changePassword: "/auth/change-password",

  //staff
  sell: "/staff",
  storeStaff: "/staff/store",
  schedule: "/staff/schedule",
  gift: "/staff/gift",
  overview: "/staff/overview",
};
